CREATE TABLE IF NOT EXISTS columns(
    id INTEGER PRIMARY KEY  AUTOINCREMENT not null,
    f_nullable INTEGER,
    f_bool BOOL not null,
    f_smallint SMALLINT not null,
    f_mediumint MEDIUMINT not null,
    f_int int  not null,
    f_integer INTEGER not null,
    f_tinyint TINYINT not null,
    f_int2 INT2 not null,
    f_int8 INT8 not null,
    f_biginteger BIGINT not null,
    f_float FLOAT not null,
    f_double DOUBLE not null,
    f_doubleprecision DOUBLE PRECISION not null,
    f_real REAL not null,
    f_datetime DATETIME not null,
    f_char CHAR not null,
    f_varchar VARCHAR(255) not null,
    f_character CHARACTER(255) not null,
    f_nvarchar NVARCHAR(255) not null,
    f_nchar NCHAR(255) not null,
    f_text TEXT not null,
    f_blob BLOB not null
) 